fantasycalendar/FoundryVTT-Sequencer

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .prettierignore
- README.md
- docs/README.md
- docs/api/animation.md
- docs/api/effect.md
- docs/api/filter.md
- docs/api/home.md
- docs/api/scrolling-text.md
- docs/api/sound.md
- docs/basics.md
- docs/changelog.md
- docs/database-basics.md
- docs/database.md
- docs/effect-manager.md
- docs/player.md
- docs/preloader.md
- docs/presets.md
- docs/sample-macros.md
- docs/section-manager.md
- docs/sidebar.md
- docs/tutorials/advanced-fire-bolt.md
- docs/tutorials/advanced-shield.md
- docs/tutorials/advanced-trap.md
- docs/tutorials/basic-linked.md
- docs/tutorials/basic-transformation.md
- package.json
Markdown files when formatted were killing some of the intentional spacing in `new Sequencer()` examples. This makes sure `md` files won't be formatted in the future and reverts the formatting that was already committed in #156.
> Fix markdown

- src/modules/sequencer-effect-manager.js
The code was \`Sequencer\`\`...\` which made "Sequencer" get interpreted as a tagged function rather than as text and try to call it, erroring. I believe the intent was \`Sequencer | ...`.
> Fixes a small typo

- src/modules/sequencer-database.js
The hardest part about this change is frankly figuring out the name but unfortunately I couldn't think of anything too illustrative. I'd be open to any changes in terms of name... or really any changes.
Here's the output:
```js
Sequencer.Database.getPathsUnder("jb2a.magic_signs.rune.02.complete"); // ["01", "02", "03", ...]
Sequencer.Database.getPathsUnder("jb2a.magic_signs.rune.02.complete", { fullyQualified: true }); // ["jb2a.magic_signs.rune.02.complete.01.blue", "jb2a.magic_signs.rune.02.complete.01.green", "jb2a.magic_signs.rune.02.complete.01.grey" ...]
```
This basically makes it both recursive and fully qualified, i.e. contains the starting portion. This way everything output is a completely valid entry name. I found a macro or two where this'd be useful.
> Add `fullyQualified` option for `Sequencer.Database.getPathsUnder`

- src/lib/canvas-lib.js
- src/sections/animation.js
As of Foundry v11, createEmbeddedDocuments returns the token document before the mesh is created. If this document is used in sequencer it would throw an error. This waits until the mesh is generated before running any animation.
> Wait for mesh to generate before animating

- src/sections/sound.js
When trying to play sounds in Foundry V12 with the new `atLocation` feature, I received an error that `atLocation` for sounds is not supported on Foundry V11 .
I believe the check in sound.js should only throw this error on foundry versions other than 12 instead of for version 12.
> Fix sound `atLocation` version check

- src/sockets.js
When trying to preload assets with for example
```js
Sequencer.Preloader.preloadForClients(['jb2a.pack_hound_missile.orange'])
```
Sequencer throws an error because `SequencerPreloader` is not in scope in the sockets.js file.
> Add missing import of SequencerPreloader

- docs/api/effect.md
- src/canvas-effects/canvas-effect.js
- src/sections/effect.js
This PR changes the way how `belowTokens` and `belowTiles` work in FoundryVTT V12.
Instead of changing the elevation to fixed offsets, which in V12 could easily render effects in unexpected order, especially on maps that make heavy use of elevations. These functions now instead set the `sortLayer` property on the effect canvas Object.
This `sortLayer` value is used in v12 to tie-break the render order of objects within the same elevation, which now sort objects first by `elevation`, secondarily by `sortLayer` and finally by the `sort` property, which is named zIndex in sequencer.
> Use `sortLayer` instead of elevation for effect layer ordering

- src/modules/sequencer-preloader.js
- src/modules/sequencer.js
With this PR, prefetching of assets when `.play({ prefetch: true })` is used is done in parallel instead of sequentially.
> Prefetch files in parallel

- module.json
- src/modules/sequencer-sound-manager.js
- src/sections/sound.js
A single lack of `?.` breaks the Sequence 🫠
> Fix the Sound fix

- src/sections/animation.js
As far as I can tell this is the only spot where it should be added. With regions, there's a new "teleport" property on token updates which is set when a region causes a teleport. By setting it when using `teleportTo` it should make sure nothing is triggered that shouldn't be for a "normal" teleportation.
> add teleport flag to updates

- src/batchShader.js
- src/lib/filters/vision-mask-filter.js
- src/module.js
This replaces the individual rendering code for the vision sample shader with a batched version. This means probably between 15 and 31 or so effects could be drawn in one drawCall[^1] with vision masking.
[^1]: Once filters for sequencer effects are not set when they are not needed
> Enable batching for vision mask shader

- src/module.js
If the batch shader is initialized before creating the extra layer and the canvas initialization, resizing / rerendering of the layer fails because the batch shader initialization depends on the canvas being ready.
This means that currently, creation of the above screen space UI effects layer fails and effects that should be played there currently are not played at all.
This PR fixes the initialization order of the batch renderer, which solves this issue.
> Fix batch shader initialization order. Fixes #299

- src/modules/sequencer-preloader.js
This fixes two issues with the current preloading of assets:
1. The `src` for the preloading operation itself was undefined which made preloading just not work...
2. When checking for the amount of files to preload, in certain cases (mainly ranged attacks with distance scaling) the `inSrcs` value consists of an array of array of file paths, which makes the surrounding call to `make_array_unique` to check for unique paths not work as intended. By applying the deepFlatten operation before the unqiue call, the amount of files to preload is more accurately calculated.
> Fix Preloading of assets

- src/canvas-effects/canvas-effect.js
- src/lib/filters/vision-mask-filter.js
- src/lib/meshes/tiling-sprite-mesh.js
This PR introduces a new class `TilingSpriteMesh` that builds upon the regular foundry spriteMesh to bring tiling capabilities without having to use `PIXI.TilingSprite`. This allows tiling texture effects and regular effects to use the same mesh and shader (which is now modified to include rendering of tiling textures).
This makes the code a little bit nicer, but more importantly allows for batching across video-based effects and tiling effects!
In this test scene with one tiling texture for every 2 regular effects, this increases the performance quite dramatically.
https://github.com/user-attachments/assets/26890719-48d3-4942-8d56-d9ae9d4dedf1
https://github.com/user-attachments/assets/d2001b2e-7e0d-47ff-8afa-ae44f8b11ed6
But why stop there... There is one filter that is very often used …
> Add tiling and ColorMatrix filter directly to sequencer effect shader

- src/lib/filters/vision-mask-filter.js
- src/module.js
The `createPlugin` code is copied from the original `BaseSamplerShader` foundry class.
Reason we need to override it here is due to the way foundry initialized the canvas and the hooks at our disposal.
The shaders "owned" by foundry are initialized directly in the canvas init function. Sadly, if we init it in the regular "init" hook, settings are not yet defined and `canvas.performance`, which the default implementation checks to essentially verify that a canvas is available, is simply not set yet.
If we init it in a canvasReady or other later hook, the "prerender" functions are called first and break because they expect the batch shaders to all be registered...
Only way around this that I could see was to skip the check if a canvas is available and register the shader as a PIXI extension …
> Fix batch shader initialization.

- typings/types.d.ts
I believe this was a typo as before the change the types basically said "either return void or a function that returns a promise of void." The documentation also states it should be just be a void-returning function, async or not.
> Update thenDo types

- src/modules/sequencer-crosshair/CrosshairsDocument.js
- src/modules/sequencer-crosshair/TokenCrosshairsDocument.js
- src/sections/crosshair.js
- typings/types.d.ts
Just some small fixes I've found during my work for PF2e Graphics:
- Typing errors:
- `CrosshairsData.snap.angle` should be `.direction`
- `CrosshairsData.snap.position` and `.size` should be numbers. `SnappingOptions` or `CONST.GRID_SNAPPING_MODES` lets you map from human-readable strings to the appropriate number, but a number is still what's ultimately desired. Trying to be smart with enums seems to cause problems down the line for TS projects depending on Sequencer (e.g. PF2e Graphics), so I think that'll have to wait for a putative TS rewrite sometime in the distant future 😏
- `CrosshairsData.location.lockOffsetDistance` was removed because it doesn't appear to exist in the code?
- `CrosshairsData.location.wallBehavior` wasn't defined (also same thing applies regarding enums as …
> Minor corrections/improvements to crosshairs

- src/canvas-effects/effects-layer.js
Two issues here. `uiEffectsLayer` has apparently been renamed to `sequencerEffectsUILayer`, and `addChild`/`removeChild` methods accessed `layer.app.stage` directly, expecting `layer` to be set instead of always using the `getLayer()` function.
> Fix fallback code path for aboveUILayer effects

- src/canvas-effects/effects-layer.js
When fixinig the fallback code for the above UI layer I forgot to update one line that activates the layer when children are added...
Apparently I only tested the fallback path then. I now tested that both paths work. Playing on the above UI layer if it is enabled and also correctly playing on the regular UI layer if the above UI layer is disabled.
> Correctly set `renderable` property on ui layer when adding children

- src/canvas-effects/sequencer-sprite-manager.js
- src/lib/meshes/AnimatedSpriteMesh.js
- src/lib/spritesheets/FramePacker.js
- src/modules/sequencer-file-cache.js
This fixes multiple errors with the current implementation of spritesheets:
1. `this` value being undefined in FramePacker.js under certain circumstances when creating scaled spritesheets for effects.
2. `result.spritesheet` accessing `spritesheet` of undefined value in sequencer-file-cache.js when a spritesheet job is accessed after the same job previously could not generate a spritesheet for any reason.
3. bidrectionally attached effects using spritesheets flickering between the actual distance between attached source and target and initial source/target distance after the related effectd for the currently active distance was first displayed
4. Effects jumping in size for one frame when switching to another related effect (for example because of distance scaling for effects attached to …
> Some spritesheet fixes

- src/lib/spritesheets/FramePacker.js
- src/lib/spritesheets/decodeWorker.js
Changes to `src/lib/spritesheets/decodeWorker.js` are just cleanup.
Many other changes were cleanup or naming changes.
Rectified mistakes were:
* The scaled buffer and sizing rectangle after resizing was not actually passed on as imageBuffer (line 172, 173).
* when trimming the images, the first pixel data (red channel) was read instead of the alpha channel.
> Fix scaling of spritesheets and alpha trimming

- src/lib/spritesheets/FramePacker.js
- src/lib/spritesheets/TextureCompressor.js
- src/lib/spritesheets/ktx2FileCache.js
Some renaming for increased clarity.
The only real change in behavior is that spritesheets are now scaled in 10% increments (100%, 90%, 80%, ... down to the minimum size) instead of halved resolutions (100%, 50%, 25%, 12,5%, ...)
This also removes the file size limit, as even 8000x8000 px textures should be okay to fit in the cache after enabling zstandard compression. 
This also resets the spritesheet cache as 0.5x scale spritesheets are quite bad in most cases...
> Prefer larger spritesheets when scaling

- src/canvas-effects/canvas-effect.js
`this._animationTimes.loopStart` can be undefined when `this._startTime` is 0...
Don't know what I was thinking when writing this :/ 
This now correctly does what I said previously: If `_startTime` is 0 (default) and a `this._animationTimes.loopStart` is defined, that value is used. Otherwise it falls back to `_startTime`.
> Fix loops when loopStart is undefined

- src/modules/sequencer-interaction-manager.js
This changes no functionality, simply omits the `document.elementFromPoint` call in case the sequencer layer is inactive.
I've not personally had any issues with performance with `document.elementFromPoint`, but I've seen the performance log of one case where each call to this function takes about 8ms. He is also using a high refresh monitor, so this function is called on each mouse move frame (independend of the canvas refresh cycle) every 6.1ms.
> Return early if sequencer layer is not active in mousemove handler

- src/canvas-effects/canvas-effect.js
- src/canvas-effects/effects-layer.js
- src/canvas-effects/sequencer-sprite-manager.js
- src/lib/meshes/TilingSpriteMesh.js
- src/modules/sequencer-file-cache.js
Discovered errors: Effects with only a text would not play because sprite.anchor was undefined and optional chaining was missing.
xRay setting was not working because the property for that setting was `isVisionMaskingEnabled`, but the setter was called `isVisionMaskEnabled`, leading to that flag never being set correctly.
Spritesheets under certain circumstances threw errors in the cleanup code. This had no effet other than console error messages being logged
> Various minor fixes

- src/canvas-effects/canvas-effect.js
This extends the the visibility update logic to hide effects that are attached to tokens when the `bindVisibility` flag is active. No need to check for ownership of the token, as hidden tokens are invisible even to the owner.
> Hide visibility-bound effects for hidden tokens for non-gm users

- src/lib/inspector-js/inspectorjs-js.d.ts
- src/lib/spritesheets/decodeWorker.js
- src/lib/spritesheets/ktx2FileCache.js
This PR aims to improve the frameRate calculation of spritesheets, using the (technically required) frame timing information in the video track instead of metadata to calculate the frameRate. It falls back to the metadata if the timing is not available (variable frameRate is a thing, but not even many players support this, no idea if web browsers do. I couldn't find a video file with actual variable frame timing)
If no frameRate can be found, spritesheet generation now bails and the video file will continue to be used for the effect.
Additionally, if an existing effect is found in the cache without frameRate timing, the cache entry is now deleted, nothing returned and the spritesheet will be calculated anew.
> Use calcualted framerate for spritesheet generation instead of metadata

- docs/api/animation.md
As title; diff is self-explanatory.
I'm not too sure what `towardsCenter` does practically (what would it point towards _if not_ the centre?), but documented it nonetheless.
> Fix animations' `rotateTowards` documentation

- src/sections/effect.js
closes [FEAT] - Add Support for Dynamic Tokens `.copySprite()` #406
> feat(copy-sprite-dyn) Add Support for Dynamic Tokens for Copy Sprite
