fantasycalendar/FoundryVTT-Sequencer

scripts/module/sections/effect.js, scripts/module/sections/sound.js, scripts/module/sequencer-audio-helper.js, scripts/sockets.js
Additionally, `fadeInAudio` and `fadeOutAudio` are also handled correctly
now for both the local and other connected clients.
=> Fix sound duration for other connected clients

.prettierrc, scripts/module/formapplications/sequencer-database-viewer.js, scripts/module/lib/cache.js, scripts/module/lib/html.js, scripts/module/lib/lib.js, templates/sequencer-database-template.html
- Implements scroll virtualisation on the database view, should be much more responsive when loading many items (such as if you have AA and JB2A)
- caches searches
- slightly tweaked search code
- Implements a few utility functions to assist with this
=> Scroll virtualisation

languages/es-ES.json, module.json
You might change/add some things for the v10 compatible version, so I will try to check again whenever that's released just in case. 😄
=> Add Spanish translation

scripts/module/sequencer.js
Fixes [this](https://github.com/League-of-Foundry-Developers/fvtt-advanced-macros/issues/46#issuecomment-1322628926) issue
=> Advanced Macros 1.19.2 Fix

scripts/formapplications/sequencer-database-viewer-ui.js, templates/sequencer-database-template.html
Supports `.ogg`, `.mp3` and `.wav`.
Proof of it working:
https://user-images.githubusercontent.com/34866157/216792820-9ad9c9c1-feda-4c84-a058-ad3828d631dc.mp4
=> Added support for sounds in the database

package-lock.json, package.json
Removes ESLint so that lint-staged doesn't try to run it.
=> Remove ESLint

src/lib/canvas-lib.js
Pretty short and sweet change, motivated by a user in the jb2a discord asking about targeting drawings. It seems to me that this is the one location that ties all the ways to target something together. Hopefully the change makes sense and covers everything!
=> Make drawings targetable

src/modules/sequencer.js
=> Fix Presets

src/canvas-effects/canvas-effect.js
Check whether the error message is up to standards
=> Add warning when stretch distance is 0

typings/types.d.ts
=> Type Updates

src/modules/sequencer.js, typings/types.d.ts
For when you want everything local and not iterate over every part of a Sequence with `.locally()`
=> Add local: boolean to .play()

typings/types.d.ts
Forgot to make the keys optional. For penance I have added a `RequireAtLeastOne` type to make it even more accurate.
=> Fix endEffects

src/sections/sound.js
=> Fix Sounds on V12

src/modules/sequencer-sound-manager.js
-debuggers and console.logs get through.
god damn it
=> When the repo has no linter-

src/lib/filters/vision-mask-filter.js
Forgott to add the tintColor again in the effects shader after finishing the colorMatrix implementation...
=> Fix effect tinting

docs/api/sound.md, module.json, src/modules/sequencer-sound-manager.js, src/sections/sound.js, src/sections/traits/audio.js, typings/types.d.ts
The code adds .audioChannel to manually change audio output
Example:
```js
new Sequence()
.sound("assets/sfx/pistol.mp3")
.audioChannel("environment")
.play()
```
=> Add .audioChannel

src/canvas-effects/canvas-effect.js, src/canvas-effects/sequencer-sprite-manager.js
There were two parts to this issue.
First is I checked the `this.isEnding` attribute (which does not exist) instead of `this._isEnding`. This prevented the effect from correctly playing the ending sequence, as the rest of the `loopHandler` function was still executed, resetting the loop even as it was ended.
Second is I always reset the startTime to the `startTime` value which is 0 by default, even when the effect specifies a looping start time. The effect is now reset to the startTime only if it is set to a value other than 0 and to the animation `loopStart` value otherwise.
=> Fix effect loops also looping the `end` portion of the effect

src/canvas-effects/canvas-effect.js
I even made sure that screen space (above ui) layer, shapes and texts are still working!
=> Add default template for custom rangefind files

src/formapplications/database/database-shell.svelte
Also makes the location of the preview a little more consistent with flexbox.
=> Fix audio controls

languages/en-EN.json, src/formapplications/database/DatabaseStore.js, src/formapplications/database/database-shell.svelte, src/modules/sequencer-database.js
Resolves #359
https://github.com/user-attachments/assets/89c93697-3331-4e2d-be48-cd914a67f7c8
=> Audio filtering 

src/modules/sequencer-database.js, typings/types.d.ts
=> More intuitive Database live-editing with `override` option

src/sections/sound.js
=> Fix #377 - Sound breaking when offset is provided

src/sections/animation.js
=> Fix #376 - Tint not working in V12

src/modules/sequencer-sound-manager.js
=> Fix sound offsets Crashing Foundry

src/canvas-effects/canvas-effect.js
=> Fix an issue regarding inconsistent screenspace effect sizes

languages/it.json
Updated with EN Fixes in v3.4.9
=> v3.4.9 it.json
